### ISSUE TITLE
`FROM scratch` containers cannot sleep

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/kubernetes-image-puller#3]
Some of the images we want to cache come from `scratch`, which does not include anything other than the built binary. This means that `sleep infinity` fails for those containers and the daemonset is never marked as `RUNNING`.

This means
1. It will be impossible to keep those containers running perpetually, as we currently expect
2. It seems to be impossible to override the entrypoint of such containers; including them in the cache would mean allowing them to run whatever their default entrypoint is. We would need to check to make sure this does not cause issues (e.g. brokers calling API endpoints).

**Comment by garagatyi** [comment]
@amisevsk Maybe it would be better to create issues for this repo in RhChe and disable issues here? Doesn't seem like this repo is going to be used outside of RhChe scope.

**Comment by ibuziuk** [comment]
I personally like main issues to be created in a dedicated repo, I did the same for che-starer for example. So matter of choice, but I like the current approach more than `all issues in rh-che`

**Comment by amisevsk** [comment]
I also prefer issues in this repo, especially if it is viewed by people outside of our team -- otherwise if SD team has a problem it's harder to check if there is an issue created. There was also talk at one point about another team being interested in caching images on the starter clusters, so it might be useful for them.

I'm pretty indifferent though; I'm happy to move issues to rhche if that's what we decide.

**Comment by ibuziuk** [comment]
@amisevsk am I correct that only Che 7 images are affected? Could you please list all the affected images?

**Comment by amisevsk** [comment]
I don't have a complete list, since I don't have a list of images we'd want to cache :). In short, yes, this only affects Che 7 images as far as I know.

- Che 6 images should be fine since they're generally based off full OS images.
- Images coming from Alpine Linux are already working (fixed by using `sleep 30d` instead of `sleep infinity`)
- The main images that are affected by this are plugin sidecar images (e.g. https://github.com/eclipse/che-machine-exec/blob/master/Dockerfile#L21) as they are often `FROM scratch`
- The JWT proxy image was giving a different error that I still need to look into, it was a strange one

I'd generally scope this as a relatively low impact issue at the moment, since the `FROM scratch` images are generally quite small already and we seem to have bigger issues with large images.

**Comment by amisevsk** [comment]
Closing this issue as:
- JWT proxy cannot be cached since it requires mounting a volume for config, and I don't want to include custom logic to cache this image
- from scratch images can only run their binary, so we'll have trouble sleeping them in any case.

This could potentially be worked around in the future using init containers instead of regular ones, but it remains to be seen.
